// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ConsumidorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumoEnergia")
                        .HasColumnType("float");

                    b.Property<bool>("ContratoAtivo")
                        .HasColumnType("bit");

                    b.Property<double>("DespesaMensalEnergia")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferenciaEnergia")
                        .HasColumnType("int");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Consumidores");
                });

            modelBuilder.Entity("Domain.Models.ProdutorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<double>("CapacidadeProducao")
                        .HasColumnType("float");

                    b.Property<int?>("ConsumidorModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicioOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEnergia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumidorModelId");

                    b.ToTable("Produtores");
                });

            modelBuilder.Entity("Domain.Models.ProdutorModel", b =>
                {
                    b.HasOne("Domain.Models.ConsumidorModel", null)
                        .WithMany("Produtores")
                        .HasForeignKey("ConsumidorModelId");
                });

            modelBuilder.Entity("Domain.Models.ConsumidorModel", b =>
                {
                    b.Navigation("Produtores");
                });
#pragma warning restore 612, 618
        }
    }
}
